name: deploy to AWS 
on:
  push
env:
  BUCKET_NAME : "aws-deployment-pco"
  AWS_REGION : "eu-north-1"

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v5

      - name: run script
        run : |
          chmod +x ./script.sh
          ./script.sh
          
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::152569707942:role/github-oidc
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
      # Upload a file to AWS s3
      - name: Copy index.html to s3
        run: |
          aws sts get-caller-identity 
          aws s3 cp ./index.html s3://${{ env.BUCKET_NAME }}/
